// Additional exercises. Equipment photos show examples, not exercise demonstrations.
const extraExerciseData = [
 {id:'db-squat',name:'Приседания с гантелью у груди',group:'dumbbells',muscles:'Ноги · ягодицы',sets:'3 × 10–12',note:'Держи гантель у груди. Опускайся в удобную глубину, колени направляй по линии стоп.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-rdl',name:'Румынская тяга с гантелями',group:'dumbbells',muscles:'Задняя поверхность бедра · ягодицы',sets:'3 × 8–12',note:'Отводи таз назад, держи гантели близко к ногам. Не округляй спину; глубина зависит от подвижности.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-lunge',name:'Обратные выпады с гантелями',group:'dumbbells',muscles:'Ноги · ягодицы',sets:'3 × 8–12',note:'Сделай шаг назад и опустись без удара коленом о пол. Повторы указаны на каждую ногу.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-row',name:'Тяга гантели с опорой на скамью',group:'dumbbells',muscles:'Спина',sets:'3 × 10–12',note:'Опирайся на скамью, не разворачивай корпус. Веди локоть к тазу. Повторы — на каждую сторону.',image:'assets/equipment/incline-bench.jpg',equipment:'Скамья для тяги с гантелью'},
 {id:'db-shoulder',name:'Жим гантелей сидя',group:'dumbbells',muscles:'Плечи · трицепс',sets:'3 × 8–12',note:'Настрой спинку скамьи близко к вертикали. Не прогибай поясницу; двигайся в комфортной амплитуде.',image:'assets/equipment/incline-bench.jpg',equipment:'Регулируемая скамья'},
 {id:'db-lateral',name:'Разведения гантелей в стороны',group:'dumbbells',muscles:'Плечи',sets:'3 × 10–15',note:'Слегка согни локти. Поднимай руки примерно до уровня плеч, без рывков.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-curl',name:'Сгибания рук с гантелями',group:'dumbbells',muscles:'Бицепс',sets:'3 × 10–15',note:'Держи локти возле корпуса. Опускай гантели плавно, не раскачивайся.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-triceps',name:'Разгибание рук с гантелью над головой',group:'dumbbells',muscles:'Трицепс',sets:'2 × 10–15',note:'Держи гантель двумя руками. Не переразгибай поясницу, выбирай комфортную амплитуду.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантель'},
 {id:'db-floor-press',name:'Жим гантелей лёжа на полу',group:'dumbbells',muscles:'Грудь · трицепс',sets:'3 × 8–12',note:'Опускай локти до мягкого касания пола и выжимай гантели без удара друг о друга.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-split-squat',name:'Сплит-присед с гантелями',group:'dumbbells',muscles:'Ноги · ягодицы',sets:'2 × 8–12',note:'Стопы остаются на месте в разножке. Опускайся вертикально и держи равновесие. Повторы — на каждую ногу.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-calf',name:'Подъёмы на носки с гантелями',group:'dumbbells',muscles:'Икры',sets:'3 × 12–20',note:'При необходимости держись за устойчивую опору. Поднимайся и опускайся плавно.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'db-rear',name:'Разведения гантелей в наклоне',group:'dumbbells',muscles:'Задняя дельта · верх спины',sets:'2 × 10–15',note:'Наклонись с нейтральной спиной. Разводи руки без раскачивания и пожимания плечами.',image:'assets/equipment/dumbbells.jpg',equipment:'Гантели'},
 {id:'treadmill-walk',name:'Ходьба на беговой дорожке',group:'cardio',muscles:'Умеренное кардио',kind:'cardio',minutes:25,sets:'25 мин',note:'Начни с 5 минут спокойной ходьбы. Выбери темп, при котором можешь говорить фразами, и закончи 3–5 минутами заминки.',image:'assets/equipment/treadmill.jpg',equipment:'Беговая дорожка'},
 {id:'treadmill-incline',name:'Ходьба с наклоном на дорожке',group:'cardio',muscles:'Кардио · ноги',kind:'cardio',minutes:20,sets:'20 мин',note:'Добавляй наклон только если обычная ходьба комфортна. Не висни на поручнях; снижай наклон или скорость при усталости.',image:'assets/equipment/treadmill.jpg',equipment:'Беговая дорожка с наклоном'},
 {id:'treadmill-jog',name:'Лёгкий бег на дорожке',group:'cardio',muscles:'Кардио',kind:'cardio',minutes:20,sets:'20 мин',note:'Начни и закончи ходьбой. Выбирай комфортный бег; если он пока труден, чередуй короткие отрезки бега и ходьбы.',image:'assets/equipment/treadmill.jpg',equipment:'Беговая дорожка'},
 {id:'treadmill-alternate',name:'Чередование ходьбы и лёгкого бега',group:'cardio',muscles:'Кардио',kind:'cardio',minutes:20,sets:'20 мин',note:'После разминки чередуй 1 минуту комфортного бега и 2 минуты ходьбы. Можно оставить только ходьбу.',image:'assets/equipment/treadmill.jpg',equipment:'Беговая дорожка'},
 {id:'bike',name:'Велотренажёр — ровный темп',group:'cardio',muscles:'Кардио · ноги',kind:'cardio',minutes:25,sets:'25 мин',note:'Настрой высоту сиденья и умеренное сопротивление. Держи ровный темп, при котором можешь говорить фразами.',image:'assets/equipment/exercise-bike.jpg',equipment:'Велотренажёр'},
 {id:'elliptical',name:'Эллиптический тренажёр',group:'cardio',muscles:'Кардио · всё тело',kind:'cardio',minutes:20,sets:'20 мин',note:'Начни с лёгкого сопротивления. Держи корпус устойчивым, не делай резких движений.',image:'assets/equipment/elliptical.jpg',equipment:'Эллиптический тренажёр'}
, {"id":"db-fly","name":"Разведения гантелей лёжа","group":"dumbbells","muscles":"Грудь","sets":"2 × 10–15","note":"Используй небольшой вес и слегка согни локти. Не опускай плечи глубоко ниже корпуса.","image":"assets/equipment/incline-bench.jpg","equipment":"Скамья и гантели"},
{"id":"db-crunch","name":"Скручивания с лёгкой гантелью","group":"dumbbells","muscles":"Пресс","sets":"2 × 10–15","note":"Ляг на пол и держи лёгкую гантель у груди. Приподнимай лопатки, без рывков шеей. Можно выполнять без гантели.","image":"assets/equipment/dumbbells.jpg","equipment":"Лёгкая гантель"},
{"id":"db-bent-row","name":"Тяга двух гантелей в наклоне","group":"dumbbells","muscles":"Спина","sets":"3 × 8–12","note":"Отведи таз назад, сохраняй устойчивую спину. Подтягивай локти к корпусу без раскачивания.","image":"assets/equipment/dumbbells.jpg","equipment":"Гантели"},
{"id":"db-supported-row","name":"Тяга гантелей с упором грудью","group":"dumbbells","muscles":"Спина","sets":"3 × 8–12","note":"Ляг грудью на наклонную скамью. Веди локти назад без подъёма корпуса.","image":"assets/equipment/incline-bench.jpg","equipment":"Наклонная скамья и гантели"}
];
